// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.
// @hook-contract useCreateInquiry(): { mutate: (vars: InquiryRequestDto, options?: MutateOptions<InquiryResponseDto, Error, InquiryRequestDto>) => void; mutateAsync: (vars: InquiryRequestDto, options?: MutateOptions<InquiryResponseDto, Error, InquiryRequestDto>) => Promise<InquiryResponseDto>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useInquiries(): { data: InquiryResponseDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useInquiryById(id: number): { data: InquiryResponseDto | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useUpdateInquiryStatus(): { mutate: (vars: { id: number; request: InquiryStatus }, options?: MutateOptions<InquiryResponseDto, Error, { id: number; request: InquiryStatus }>) => void; mutateAsync: (vars: { id: number; request: InquiryStatus }, options?: MutateOptions<InquiryResponseDto, Error, { id: number; request: InquiryStatus }>) => Promise<InquiryResponseDto>; isPending: boolean; isError: boolean; error: Error | null }

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { MutateOptions } from '@tanstack/react-query';
import { createInquiry, getAllInquiries, getInquiryById, updateInquiryStatus } from '@/services/inquiryService';
import type { InquiryRequestDto, InquiryResponseDto, InquiryStatus } from '@/types/inquiry';

export function useCreateInquiry(): { mutate: (vars: InquiryRequestDto, options?: MutateOptions<InquiryResponseDto, Error, InquiryRequestDto>) => void; mutateAsync: (vars: InquiryRequestDto, options?: MutateOptions<InquiryResponseDto, Error, InquiryRequestDto>) => Promise<InquiryResponseDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: InquiryRequestDto) => createInquiry(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['inquiry'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useInquiries(): { data: InquiryResponseDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['inquiry', 'getAllInquiries'], queryFn: getAllInquiries });
  return { data, isLoading, isError, error };
}

export function useInquiryById(id: number): { data: InquiryResponseDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['inquiry', 'getInquiryById', id], queryFn: () => getInquiryById(id) });
  return { data, isLoading, isError, error };
}

export function useUpdateInquiryStatus(): { mutate: (vars: { id: number; request: InquiryStatus }, options?: MutateOptions<InquiryResponseDto, Error, { id: number; request: InquiryStatus }>) => void; mutateAsync: (vars: { id: number; request: InquiryStatus }, options?: MutateOptions<InquiryResponseDto, Error, { id: number; request: InquiryStatus }>) => Promise<InquiryResponseDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: number; request: InquiryStatus }) => updateInquiryStatus(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['inquiry'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
