// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.
// @hook-contract useLookbookEntries(): { data: LookbookEntryDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useLookbookEntryById(id: number): { data: LookbookEntryDto | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useCreateLookbookEntry(): { mutate: (vars: LookbookEntryDto, options?: MutateOptions<LookbookEntryDto, Error, LookbookEntryDto>) => void; mutateAsync: (vars: LookbookEntryDto, options?: MutateOptions<LookbookEntryDto, Error, LookbookEntryDto>) => Promise<LookbookEntryDto>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useUpdateLookbookEntry(): { mutate: (vars: { id: number; request: LookbookEntryDto }, options?: MutateOptions<LookbookEntryDto, Error, { id: number; request: LookbookEntryDto }>) => void; mutateAsync: (vars: { id: number; request: LookbookEntryDto }, options?: MutateOptions<LookbookEntryDto, Error, { id: number; request: LookbookEntryDto }>) => Promise<LookbookEntryDto>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useDeleteLookbookEntry(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null }

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { MutateOptions } from '@tanstack/react-query';
import { getAllLookbookEntries, getLookbookEntryById, createLookbookEntry, updateLookbookEntry, deleteLookbookEntry } from '@/services/lookbookService';
import type { LookbookEntryDto } from '@/types/lookbook';

export function useLookbookEntries(): { data: LookbookEntryDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['lookbook', 'getAllLookbookEntries'], queryFn: getAllLookbookEntries });
  return { data, isLoading, isError, error };
}

export function useLookbookEntryById(id: number): { data: LookbookEntryDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['lookbook', 'getLookbookEntryById', id], queryFn: () => getLookbookEntryById(id) });
  return { data, isLoading, isError, error };
}

export function useCreateLookbookEntry(): { mutate: (vars: LookbookEntryDto, options?: MutateOptions<LookbookEntryDto, Error, LookbookEntryDto>) => void; mutateAsync: (vars: LookbookEntryDto, options?: MutateOptions<LookbookEntryDto, Error, LookbookEntryDto>) => Promise<LookbookEntryDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: LookbookEntryDto) => createLookbookEntry(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['lookbook'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateLookbookEntry(): { mutate: (vars: { id: number; request: LookbookEntryDto }, options?: MutateOptions<LookbookEntryDto, Error, { id: number; request: LookbookEntryDto }>) => void; mutateAsync: (vars: { id: number; request: LookbookEntryDto }, options?: MutateOptions<LookbookEntryDto, Error, { id: number; request: LookbookEntryDto }>) => Promise<LookbookEntryDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: number; request: LookbookEntryDto }) => updateLookbookEntry(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['lookbook'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteLookbookEntry(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: number) => deleteLookbookEntry(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['lookbook'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
