// GENERATED from the backend API contract — do not edit by hand.
// One TanStack hook per service function — generated by FrontendHookGenerator.
// @hook-contract useProducts(): { data: ProductDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useProductById(id: number): { data: ProductDto | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useCategories(): { data: ProductCategoryDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useCategoryById(id: number): { data: ProductCategoryDto | undefined; isLoading: boolean; isError: boolean; error: Error | null }
// @hook-contract useCreateProduct(): { mutate: (vars: ProductDto, options?: MutateOptions<ProductDto, Error, ProductDto>) => void; mutateAsync: (vars: ProductDto, options?: MutateOptions<ProductDto, Error, ProductDto>) => Promise<ProductDto>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useUpdateProduct(): { mutate: (vars: { id: number; request: ProductDto }, options?: MutateOptions<ProductDto, Error, { id: number; request: ProductDto }>) => void; mutateAsync: (vars: { id: number; request: ProductDto }, options?: MutateOptions<ProductDto, Error, { id: number; request: ProductDto }>) => Promise<ProductDto>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useDeleteProduct(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useCreateCategory(): { mutate: (vars: ProductCategoryDto, options?: MutateOptions<ProductCategoryDto, Error, ProductCategoryDto>) => void; mutateAsync: (vars: ProductCategoryDto, options?: MutateOptions<ProductCategoryDto, Error, ProductCategoryDto>) => Promise<ProductCategoryDto>; isPending: boolean; isError: boolean; error: Error | null }
// @hook-contract useUpdateCategory(): { mutate: (vars: { id: number; request: ProductCategoryDto }, options?: MutateOptions<ProductCategoryDto, Error, { id: number; request: ProductCategoryDto }>) => void; mutateAsync: (vars: { id: number; request: ProductCategoryDto }, options?: MutateOptions<ProductCategoryDto, Error, { id: number; request: ProductCategoryDto }>) => Promise<ProductCategoryDto>; isPending: boolean; isError: boolean; error: Error | null }

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { MutateOptions } from '@tanstack/react-query';
import { getAllProducts, getProductById, getAllCategories, getCategoryById, createProduct, updateProduct, deleteProduct, createCategory, updateCategory } from '@/services/productService';
import type { ProductCategoryDto, ProductDto } from '@/types/product';

export function useProducts(): { data: ProductDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['product', 'getAllProducts'], queryFn: getAllProducts });
  return { data, isLoading, isError, error };
}

export function useProductById(id: number): { data: ProductDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['product', 'getProductById', id], queryFn: () => getProductById(id) });
  return { data, isLoading, isError, error };
}

export function useCategories(): { data: ProductCategoryDto[] | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['product', 'getAllCategories'], queryFn: getAllCategories });
  return { data, isLoading, isError, error };
}

export function useCategoryById(id: number): { data: ProductCategoryDto | undefined; isLoading: boolean; isError: boolean; error: Error | null } {
  const { data, isLoading, isError, error } = useQuery({ queryKey: ['product', 'getCategoryById', id], queryFn: () => getCategoryById(id) });
  return { data, isLoading, isError, error };
}

export function useCreateProduct(): { mutate: (vars: ProductDto, options?: MutateOptions<ProductDto, Error, ProductDto>) => void; mutateAsync: (vars: ProductDto, options?: MutateOptions<ProductDto, Error, ProductDto>) => Promise<ProductDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: ProductDto) => createProduct(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateProduct(): { mutate: (vars: { id: number; request: ProductDto }, options?: MutateOptions<ProductDto, Error, { id: number; request: ProductDto }>) => void; mutateAsync: (vars: { id: number; request: ProductDto }, options?: MutateOptions<ProductDto, Error, { id: number; request: ProductDto }>) => Promise<ProductDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: number; request: ProductDto }) => updateProduct(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useDeleteProduct(): { mutate: (vars: number, options?: MutateOptions<void, Error, number>) => void; mutateAsync: (vars: number, options?: MutateOptions<void, Error, number>) => Promise<void>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (id: number) => deleteProduct(id),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useCreateCategory(): { mutate: (vars: ProductCategoryDto, options?: MutateOptions<ProductCategoryDto, Error, ProductCategoryDto>) => void; mutateAsync: (vars: ProductCategoryDto, options?: MutateOptions<ProductCategoryDto, Error, ProductCategoryDto>) => Promise<ProductCategoryDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: (request: ProductCategoryDto) => createCategory(request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}

export function useUpdateCategory(): { mutate: (vars: { id: number; request: ProductCategoryDto }, options?: MutateOptions<ProductCategoryDto, Error, { id: number; request: ProductCategoryDto }>) => void; mutateAsync: (vars: { id: number; request: ProductCategoryDto }, options?: MutateOptions<ProductCategoryDto, Error, { id: number; request: ProductCategoryDto }>) => Promise<ProductCategoryDto>; isPending: boolean; isError: boolean; error: Error | null } {
  const queryClient = useQueryClient();
  const { mutate, mutateAsync, isPending, isError, error } = useMutation({
    mutationFn: ({ id, request }: { id: number; request: ProductCategoryDto }) => updateCategory(id, request),
    onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['product'] }); },
  });
  return { mutate, mutateAsync, isPending, isError, error };
}
