import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { format } from 'date-fns';
import { CalendarIcon } from 'lucide-react';
import { toast } from 'sonner';

import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Calendar } from '@/components/ui/calendar';
import { cn } from '@/lib/utils';

import { LookbookEntryDto } from '@/types/lookbook';
import { useCreateLookbookEntry, useUpdateLookbookEntry } from '@/hooks/lookbookHooks';

const formSchema = z.object({
  title: z.string().min(1, 'Title is required'),
  content: z.string().min(1, 'Content is required'),
  imageUrl: z.string().url('Invalid URL').min(1, 'Image URL is required'),
  publicationDate: z.date({ required_error: 'Publication date is required' }),
});

interface LookbookFormProps {
  entry: LookbookEntryDto | null;
  onClose: () => void;
  onSuccess: () => void;
}

export default function LookbookForm({ entry, onClose, onSuccess }: LookbookFormProps) {
  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      title: '',
      content: '',
      imageUrl: '',
      publicationDate: new Date(),
    },
  });

  const createLookbookEntryMutation = useCreateLookbookEntry();
  const updateLookbookEntryMutation = useUpdateLookbookEntry();

  useEffect(() => {
    if (entry) {
      form.reset({
        title: entry.title,
        content: entry.content,
        imageUrl: entry.imageUrl,
        publicationDate: new Date(entry.publicationDate),
      });
    } else {
      form.reset({
        title: '',
        content: '',
        imageUrl: '',
        publicationDate: new Date(),
      });
    }
  }, [entry, form]);

  const onSubmit = async (values: z.infer<typeof formSchema>) => {
    try {
      if (entry) {
        await updateLookbookEntryMutation.mutateAsync({
          id: entry.id,
          request: {
            id: entry.id,
            title: values.title,
            content: values.content,
            imageUrl: values.imageUrl,
            publicationDate: values.publicationDate.toISOString().split('T')[0],
          },
        });
        toast.success('Lookbook entry updated successfully!');
      } else {
        await createLookbookEntryMutation.mutateAsync({
          id: 0, // ID is generated by the backend
          title: values.title,
          content: values.content,
          imageUrl: values.imageUrl,
          publicationDate: values.publicationDate.toISOString().split('T')[0],
        });
        toast.success('Lookbook entry created successfully!');
      }
      onSuccess();
      onClose();
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : 'Failed to save lookbook entry.',
      );
    }
  };

  const isPending = createLookbookEntryMutation.isPending || updateLookbookEntryMutation.isPending;

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
        <FormField
          control={form.control}
          name="title"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Title</FormLabel>
              <FormControl>
                <Input data-testid="lookbook-title" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="content"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Content</FormLabel>
              <FormControl>
                <Textarea data-testid="lookbook-content" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="imageUrl"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Image URL</FormLabel>
              <FormControl>
                <Input data-testid="lookbook-imageUrl" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="publicationDate"
          render={({ field }) => (
            <FormItem className="flex flex-col">
              <FormLabel>Publication Date</FormLabel>
              <Popover>
                <PopoverTrigger asChild>
                  <FormControl>
                    <Button
                      variant={'outline'}
                      className={cn(
                        'w-full pl-3 text-left font-normal',
                        !field.value && 'text-muted-foreground',
                      )}
                      data-testid="lookbook-publicationDate-trigger"
                    >
                      {field.value ? (
                        format(field.value, 'PPP')
                      ) : (
                        <span>Pick a date</span>
                      )}
                      <CalendarIcon className="ml-auto h-4 w-4 opacity-50" />
                    </Button>
                  </FormControl>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={field.value}
                    onSelect={field.onChange}
                    disabled={(date) =>
                      date > new Date() || date < new Date('1900-01-01')
                    }
                    autoFocus
                  />
                </PopoverContent>
              </Popover>
              <FormMessage />
            </FormItem>
          )}
        />
        <div className="flex justify-end space-x-2">
          <Button type="button" variant="outline" onClick={onClose} data-testid="lookbook-cancel">
            Cancel
          </Button>
          <Button type="submit" disabled={isPending} data-testid="lookbook-submit">
            {isPending ? 'Saving...' : entry ? 'Update Entry' : 'Create Entry'}
          </Button>
        </div>
      </form>
    </Form>
  );
}